[versions]
agp_version = "8.2.0-rc02"
kotlin_version = "1.9.10"
coroutines_version = "1.7.3"
ksp_version = "1.9.10-1.0.13"
serialization_json_version = "1.6.0"

koin_version = "3.5.0"
compose_bom_version = "2023.10.01"
compose_compiler_version = "1.5.3"
accompanist_version = "0.32.0"
voyager = "1.0.0-rc10"
lottie-compose = "5.2.0"

kotlinpoet = "1.14.2"
coil_version = "2.4.0"
utilcodex_version = "1.31.1"

# androidx
appcompat = "1.6.1"
core-ktx = "1.12.0"
palette-ktx = "1.0.0"
dynamicanimation-ktx = "1.0.0-alpha03"
startup-runtime = "1.2.0-alpha02"
constraintlayout = "2.1.4"
coordinatorlayout = "1.2.0"
gridlayout = "1.0.0"
recyclerview = "1.3.1"
activity-compose = "1.8.0"
lifecycle_version = "2.6.2"
navigation_version = "2.7.4"
room_version = "2.5.2"
media = "1.7.0-alpha01"


[libraries]
# kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin_version" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin_version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines_version" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines_version" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization_json_version" }

# compose
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose_compiler_version" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose_bom_version" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-compose" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-bottomSheetNavigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-androidx = { module = "cafe.adriel.voyager:voyager-androidx", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist_version" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist_version" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist_version" }

# koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin_version" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin_version" }

# coil
# https://github.com/coil-kt/coil
# Apache-2.0 License
# 图片加载库
coil = { module = "io.coil-kt:coil", version.ref = "coil_version" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil_version" }

# androidx
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette-ktx" }
dynamicanimation-ktx = { module = "androidx.dynamicanimation:dynamicanimation-ktx", version.ref = "dynamicanimation-ktx" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle_version" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle_version" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle_version" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle_version" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation_version" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room_version" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room_version" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room_version" }
media = { module = "androidx.media:media", version.ref = "media" }

# thirdparty / others
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
ksp-symbol-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp_version" }

# [Apache-2.0 License] 安卓工具类库 https://github.com/Blankj/AndroidUtilCode/
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex_version" }


[plugins]
application = { id = "com.android.application", version.ref = "agp_version" }
library = { id = "com.android.library", version.ref = "agp_version" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }


[bundles]
common = ["kotlin-stdlib", "kotlinx-coroutines-core", "kotlinx-coroutines-android"]
accompanist = ["accompanist-flowlayout", "accompanist-permissions", "accompanist-systemuicontroller"]
compose-debug = ["compose-tooling", "compose-tooling-preview"]
compose = [
    "compose-bom",
    "compose-ui",
    "compose-ui-util",
    "compose-ui-graphics",
    "compose-ui-viewbinding",
    "compose-foundation",
    "compose-material",
    "compose-material3",
    "compose-material3-window-size",
    "compose-runtime-livedata",
]
voyager = [
    "voyager-navigator",
    "voyager-tabNavigator",
    "voyager-transitions",
    "voyager-androidx",
    "voyager-koin"
]